<!doctype html>
<html lang="cs">
<head>
	<meta charset="utf-8">
	<title><?= $title;?></title>
	<meta name="description" lang="cs" content="<?= $description;?>">
	<script src="bower_components/jquery/dist/jquery.min.js"></script>
	<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="css/main.css">

</head>
<body>
	<nav id="header" class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Zobrazit/Skrýt navigaci</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">odTimeTracker</a>
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li>
						<a href="#" data-toggle="collapse" data-target="#dashboardFilter" aria-expanded="false" aria-controls="dashboardFilter" title="Filter">
							<span class="glyphicon glyphicon-wrench"></span>
						</a>
					</li>
				</ul>
				<form class="navbar-form navbar-left" role="search">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
							<span class="glyphicon glyphicon-menu-hamburger"></span>
							<!-- <span class="caret"></span> -->
						</a>
						<ul class="dropdown-menu">
							<li><a href="#">Dashboard</a></li>
							<li><a href="#">Reports</a></li>
							<li><a href="#">Statistics</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">Organize</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">Log-out</a></li>
						</ul>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>	

	<!-- Filter -->
	<div id="dashboardFilter" class="panel panel-default collapse">
		<div class="panel-body">
			<p><strong style="color:#f30;">XXX Filter ...</strong></p>
		</div>
		<div class="panel-footer">
			<button type="button" class="btn btn-primary">Potvrdit</button>
			<button type="button" class="btn btn-default" data-toggle="collapse" data-target="#dashboardFilter" aria-expanded="false" aria-controls="dashboardFilter">Zavřít</button>
		</div>
	</div><!-- /#dashboardFilter -->

	<!-- Content -->
	<div id="content" role="main">
		<!-- Content will be render here... -->
	</div><!-- /#content -->

	<!-- <div class="page-footer" role="contentinfo">
		<hr><p><?= $copyright;?></p>
	</div> -->

	<!-- JavaScript -->
	<script src="scripts/main.js"></script>
	<script>
$(window).load(odTimeTracker.onLoad);
$(window).unload(odTimeTracker.onUnload);
	</script>
</body>
</html>
