<!doctype html>
<html lang="cs">
<head>
	<meta charset="utf-8">
	<title><?= $title;?></title>
	<meta name="description" lang="cs" content="<?= $description;?>">
	<script src="bower_components/jquery/dist/jquery.min.js"></script>
	<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap-theme.min.css">
	<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container">
		<div class="page-header">
			<h1>
				<a href="<?= $blogUrl;?>"><?= $title;?></a>
				<?php if (isset($subtitle)):?>
				<small><?= $subtitle;?></small>
				<?php endif;?>
			</h1>
		</div>
		<div id="content" role="main">
			<div id="post-<?= $post->getId();?>" class="post">
				<div class="post-header">
					<h2><?= $post->getSubject();?></h2>
				</div>
				<div class="post-content">
					<?= $post->getContent();?>
				</div>
				<div class="post-meta">
					<p>
						Autor: <b><?= $post->getUser()->getDisplayName();?></b>,
						Vytvořeno: <i><?= $post->getCreated()->format('j.n.Y G:i');?></i>,
						Kategorie: <a href="<?= $blogUrl . '?c=' . $post->getCategory()->getId();?>"><?= $post->getCategory()->getName();?></a>
					</p><hr>
				</div>
				<h3>Komentáře</h3>
				<?php if (count($comments) > 0):?>
					<?php foreach ($comments as $comment):?>
					<div class="well">
						<div class="post-comment-header">
							<h5>
								<?= $comment->getSubject();?>
								<small><?= $comment->getSender();?>, <?= $comment->getCreated()->format('j.n.Y G:i');?></small>
							</h5>
						</div>
						<div class="post-comment-content">
							<?= $comment->getContent();?>
						</div>
					</div>
					<?php endforeach;?>
				<?php else:?>
					<p id="no-comments-msg">Prozatím nebyly přidány žádné komentáře&hellip;</p>
				<?php endif;?>
				<hr id="comments-separator">
				<h4>Nový komentář</h4>
				<?php if ($form->isSubmitted() === true && $form->isValid() === true):?>
				<p><?= $formResultMsg;?></p>
				<?php else:?>
				<?= $form->render();?>
				<?php endif;?>
			</div>
		</div>
		<div class="page-footer" role="contentinfo">
			<hr><p><?= $copyright;?></p>
		</div>
	</div>
	<?php if ($form->isSubmitted() !== true || $form->isValid() !== true):?>
	<script>
$("#<?= $form->getName()?>").submit(function (event) {
	event.preventDefault();
	$.post('/insert-comment', $(this).serialize(), function (response) {

console.log(response);

		// Pokud jsou chyby, tak je pridame k chybne zadanym polozkam
		if (response.resultType === "validation-error") {
			// sender
			if ("senderError" in response) {
				$("#senderInput").after('<p class="bg-danger">' + response.senderError + '</p>');
			}
			// subject
			if ("subjectError" in response) {
				$("#subjectInput").after('<p class="bg-danger">' + response.subjectError + '</p>');
			}
			// content
			if ("contentError" in response) {
				$("#contentInput").after('<p class="bg-danger">' + response.contentError + '</p>');
			}
			return;
		}
		// Pokud je odpoved v poradku, tak zobrazime novy komentar (misto data dame "Před chvílí!")
		if (response.resultType === "success") {
			$("#no-comments-msg").remove();
			$(
				'<div class="well">' +
					'<div class="post-comment-header">' +
						'<h5>' + response.comment.subject + ' <small>' + response.comment.sender + ', <i>před chvílí</i></small></h5>' +
					'</div>' +
					'<div class="post-comment-content">' + response.comment.content + '</div>' +
				'</div>'
			).insertBefore("#comments-separator");
		}
		// Hodnoty byly v poradku, takze odstranime formular a nahradime jej `resultMsg`
		$("#newCommentForm").replaceWith("<p>" + response.resultMsg + "</p>");
	});
});
	</script>
	<?php endif;?>
</body>
</html>